.TH "CalCul" "1" "25\ \&DECEMBER\ \&2019" "CalCul" "CalCul1"
.SH "NAME"
Calculator for Linux
.PP
.SH "SYNOPSIS"
.B calcul
.PP
.SH "DESCRIPTION"
Console calculator for two operands
.PP
.SH "EXAMPLE"
Enter first number: 7
.PP
Enter second number: 8
.PP
Enter operation: *
.PP
a * b = 56
.PP
.SH "AUTHORS"
Nekrasova Anna <necrasova.anna@yandex.ru>